WIP: automerge the daily Dependabot PRs
domainr/whoistest pull request #24
Opened 2020-09-03 17:29 UTC by case

2020-09-05 14:06 UTC, ydnar approved these changes
Nice! 

Might want to rename this file (.yaml).

2020-10-17 22:14 UTC, ydnar requested changes

2020-10-17 22:14 UTC, ydnar commented on .github/workflows/automerge.yaml
> +#     runs-on: ubuntu-latest
These three lines are still needed. The `if` directive is within a job.

2020-10-18 02:01 UTC, case commented on .github/workflows/automerge.yaml
> +#     runs-on: ubuntu-latest
👍

2020-10-18 02:06 UTC, case commented
Ok, have another look!

2020-10-18 14:11 UTC, ydnar approved these changes

2020-10-18 14:12 UTC, ydnar commented
Do we only want to automerge `zonedb` changes?

2020-10-18 14:21 UTC, case commented
Yeah, ideally we would constrain this further to just the ZoneDB dep.





On Sun, Oct 18, 2020 at 07:12 Randy Reddig <notifications@github.com> wrote:

> Do we only want to automerge zonedb changes?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/domainr/whoistest/pull/24#issuecomment-711173652>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAE5CP5PK6EY2ERJFKKGD3SLLZV7ANCNFSM4QVGVGSA>
> .
>

2020-10-18 16:20 UTC, case commented
There might be something in here we can use?

https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context

Examples:

- The PR names look like this: "Bump github.com/zonedb/zonedb from 1.0.2794 to 1.0.2795"
- Branch names look like this: "`dependabot` merged 1 commit into `main` from `dependabot/go_modules/github.com/zonedb/zonedb-1.0.2795`"
- The PR description text starts with: "Bumps github.com/zonedb/zonedb from 1.0.2794 to 1.0.2795."

2020-10-18 16:23 UTC, case commented
Re: fetching some PR metadata we can use: https://github.community/t/how-to-get-pr-branch-name-in-github-actions/16598/6

> this produced the branch to be merged as expected:
> `github.event.pull_request.head.ref`

Or:

> `${{ github.event.pull_request.title }}`

2020-10-18 16:27 UTC, case commented
But… what we'd ideally be checking for is that the `github.com/zonedb/zonedb` line in `go.mod` is what changed.

2020-10-18 21:20 UTC, merged